version: "3.9"

services:
    db:
        image: postgres
        container_name: postgres_server
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        networks:
            - my_project_elasticsearch
        ports:
          - "5437:5432"
    elastisearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        container_name: elasticsearch_server
        environment:
            - discovery.type=single-node
        networks:
            - my_project_elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        ulimits:
            memlock:
                soft: -1
                hard: -1
#        volumes:
#            - ./usr/share/elasticsearch/data
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.1
        container_name: kibana_server
        ports:
          - "5601:5601"
#        volumes:
#          - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    clients_data_app:
        build: .
        command: >
            sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:9000"
        ports:
          - "9000:9000"
        volumes:
          - .:/app
        container_name: django_app
        depends_on:
            - db
        networks:
          - my_project_elasticsearch


networks:
    my_project_elasticsearch:
        external: true

#volumes:
#    data