version: "3.9"

services:
    database:
        image: postgres
        container_name: postgres_server
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        networks:
            - network_local
        ports:
          - "5437:5432"
#    elasticsearch_server:
#        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
#        container_name: elasticsearch_server
#        environment:
#            - discovery.type=single-node
#        networks:
#            - network_local
#        ports:
#            - "9200:9200"
#            - "9300:9300"
#        ulimits:
#            memlock:
#                soft: -1
#                hard: -1
#        deploy: # defining limit of use memory ram and CPU
#            resources:
#                limits:
#                    cpus: "0.70"
#                    memory: 5000M
#    kibana:
#        image: docker.elastic.co/kibana/kibana:7.13.1
#        container_name: kibana_server
#        ports:
#          - "5601:5601"
##        volumes:
##          - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    django:
        build: .
        command: >
            sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:9000"
        ports:
          - "9000:9000"
        volumes:
          - .:/app
        container_name: django_app
        depends_on:
            - database
        networks:
          - network_local


networks:
    network_local:
        external: true
