# Generated by Django 3.2.4 on 2021-07-10 23:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=12, verbose_name='RG')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('sex', models.CharField(choices=[('feminino', 'feminino'), ('masculino', 'masculino')], max_length=9, verbose_name='Sex')),
                ('sign', models.CharField(choices=[('Áries', 'Áries'), ('Touro', 'Touro'), ('Gêmeos', 'Gêmeos'), ('Câncer', 'Câncer'), ('Leão', 'Leão'), ('Virgem', 'Virgem'), ('Libra', 'Libra'), ('Escorpião', 'Escorpião'), ('Sagitário', 'Sagitário'), ('Capricórnio', 'Capricórnio'), ('Aquário', 'Aquário'), ('Peixes', 'Peixes')], max_length=15, verbose_name='Sign')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Mother Name')),
                ('father_name', models.CharField(max_length=250, verbose_name='Father Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
                ('height', models.FloatField(verbose_name='Height')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('type_blood', models.CharField(max_length=3, verbose_name='Type blood')),
                ('favorite_color', models.CharField(max_length=20, verbose_name='Favorite color')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.people', verbose_name='client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
