# Generated by Django 3.2.4 on 2021-06-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1, verbose_name='Sex'),
        ),
    ]
