# Generated by Django 3.2.4 on 2021-10-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensdopedido',
            name='pedido_item',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo',
        ),
        migrations.AddField(
            model_name='itensdopedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.pedido'),
            preserve_default=False,
        ),
    ]
