# Generated by Django 3.2.4 on 2021-06-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_people_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=9, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='people',
            name='telefone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
