# Generated by Django 3.2.4 on 2021-10-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20211011_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensdopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.pedido'),
        ),
    ]
