# Generated by Django 3.2.4 on 2021-10-14 22:23

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_itensdopedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
    ]
